# Generated by Django 4.1.7 on 2023-02-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whiskybase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottling_serie', models.CharField(blank=True, max_length=255, null=True)),
                ('stated_age', models.CharField(blank=True, max_length=255, null=True)),
                ('bottled', models.CharField(blank=True, max_length=255, null=True)),
                ('added_on', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('distillery', models.CharField(blank=True, max_length=255, null=True)),
                ('casknumber', models.CharField(blank=True, max_length=255, null=True)),
                ('Title', models.CharField(blank=True, max_length=255, null=True)),
                ('bottled_for', models.CharField(blank=True, max_length=255, null=True)),
                ('bottler', models.CharField(blank=True, max_length=255, null=True)),
                ('distilleries', models.CharField(blank=True, max_length=255, null=True)),
                ('casktype', models.CharField(blank=True, max_length=255, null=True)),
                ('market', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('strength', models.CharField(blank=True, max_length=255, null=True)),
                ('vintage', models.CharField(blank=True, max_length=255, null=True)),
                ('whiskybase_id', models.CharField(blank=True, max_length=255, null=True)),
                ('calculated_age', models.CharField(blank=True, max_length=255, null=True)),
                ('bottle_code', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_bottles', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='whiskybase',
            index=models.Index(fields=['bottling_serie', 'stated_age', 'bottled', 'added_on', 'url', 'image', 'distillery', 'casknumber', 'Title', 'bottled_for', 'bottler', 'distilleries', 'casktype', 'market', 'category', 'strength', 'vintage', 'whiskybase_id', 'calculated_age', 'bottle_code', 'label', 'number_of_bottles', 'size', 'barcode'], name='filter_api__bottlin_efe90a_idx'),
        ),
    ]
